#!/bin/bash

# Check if the configuration file exists
config_file="/.ingress_ice"
screenshot_folder="/screenshots/"
if ! [[ -r "$config_file" ]]
then
	echo "The configuration file does not exists. Please create it first and then specify it as a docker volume!" >&2
	exit 1
fi

config_string=($(cat "$config_file"))

# Replace path to screenshot-folder-volume
if [[ "${config_string[0]}" == 1 ]] || [[ "${config_string[0]}" == 2 ]]
then
	config_string[9]="$screenshot_folder"
else
	config_string[8]="$screenshot_folder"
fi

# Make screenshots writeable to host
umask 0000

/usr/bin/phantomjs /ingress-ice/ice.js ${config_string[*]}
